### ISSUE TITLE
Building is totally fine but I am getting an issue regarding dependencies.

### ISSUE THREAD

**Issue by Arman001** [microsoft/CryptoNets#2] opened 2019-07-11 11:07 UTC
I am getting error regarding HE Wrapper Assembly, kindly check the following attachement: 
![image](https://user-images.githubusercontent.com/21517793/61046047-9abe7980-a3f5-11e9-8a0d-0b9439066714.png)
I am waiting for a quick solution.
Thank You!

**Comment by ranigb** [comment] 2019-08-03 07:14
It seems as if the He Wrapper failed to compile. Can you send more details to allow us to reproduce? Are you targeting x64?

**Comment by ranigb** [comment] 2019-08-22 11:06
I am assuming that this issue is resolved since we are not seeing any response. Therefore, I am closing this issue.

**Comment by ranigb** [comment] 2019-08-22 11:06
I am assuming that this issue is resolved since we are not seeing any response. Therefore, I am closing this issue.

**Closed by ranigb** 2019-08-22 11:06 UTC
